### ISSUE TITLE
Connection to metamask

### ISSUE THREAD

**Issue by TGrandjeanLIST** [joze144/private-eth-poa-net#1]
Hello, did you manage to connect the eth poa network  created with a metamask wallet running on the host ?
Thanks

**Comment by joze144** [comment]
> Hello, did you manage to connect the eth poa network created with a metamask wallet running on the host ? Thanks

Hey, this project is quite old already. At that point it worked with Metamask, but now you would probably have to use newer version of geth for RPC nodes

**Comment by TGrandjeanLIST** [comment]
Hello, thanks for the reply. I installed on a Virtual Machine and I have now been able to determine that my issues are on the network management side, ( between Virtual Box and Docker .... ) direct install on the host is working. I will up date the version thanks.
